version: "3"

services:
  meetkettle:
    container_name: meetkettle
    image: ameer1234567890/meetkettle
    environment:
      - TZ=Asia/Karachi
    ports:
      - 6338:6338
    volumes:
      - ./db:/kettle/db
      - ./cert:/kettle/cert
    restart: unless-stopped
